### ISSUE TITLE
inplace abn=1.1.0 is very difficult to install

### ISSUE THREAD

**Issue by Kaile-Du** [witdsl/KRT-MLCIL#1]
Very good work. inplace_abn=1.1.0 is very difficult to install in conda environment. Can the author provide any advice

**Comment by luo-haoyu** [comment]
Thank you! You can refer to the requirement.txt, paying attention to the version of cuda and torch, or you can ask for help in the [inplace-abn](https://github.com/mapillary/inplace_abn)
